env:
  TZ: "Europe/Amsterdam"

service:
  main:
    ports:
      http:
        port: 7878

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
  media:
    enabled: true
    existingClaim: nfs-media
    mountPath: /media