apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-nextcloud
spec:
  capacity:
    storage: 3600Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.10
    path: /mnt/media-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3600Gi
  volumeName: nfs-media-nextcloud
  storageClassName: ""
