nextcloud:
  host: 192.168.50.108
  username: cedric
  password: yourpassword
  trustedDomains:
    - 192.168.50.108
    - localhost
    - 10.42.0.0/16

  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' => array(
          0 => 'localhost',
          1 => '192.168.50.108',
          2 => '10.42.0.0/16',
        ),
        'overwriteprotocol' => 'http',
      );

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi

extraVolumes:
  - name: nfs-media
    persistentVolumeClaim:
      claimName: nfs-media

extraVolumeMounts:
  - name: nfs-media
    mountPath: /mnt/media-storage