nextcloud:
  host: 192.168.50.108
  username: admin
  password: ijasd-oeuqnr-90
  trustedDomains:
    - 192.168.50.108
    - localhost
    - 10.42.0.0/16

  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' => array(
          0 => 'localhost',
          1 => '192.168.50.108',
          2 => '10.42.0.0/16',
        ),
        'overwriteprotocol' => 'http',
      );

  extraVolumes:
    - name: nfs-media
      persistentVolumeClaim:
        claimName: nfs-media

  extraVolumeMounts:
    - name: nfs-media
      mountPath: /mnt/media-storage

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi