env:
  TZ: "Europe/Amsterdam"

service:
  main:
    ports:
      http:
        port: 9696

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi

defaultPodOptions:
  securityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
