minecraftServer:
  eula: true
  serverName: "Cedrics Server"
  difficulty: normal
  maxPlayers: 20
  gameMode: survival
  levelSeed: ""
  onlineMode: true
  serviceType: LoadBalancer

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 2000m

persistence:
  storageClass: longhorn
  dataDir:
    enabled: true

extraInitContainers: |
  - name: setup-mtu
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
        ip route change default via $(ip route | grep default | awk '{print $3}') dev eth0 mtu 1280
    securityContext:
      capabilities:
        add:
          - NET_ADMIN