minecraftServer:
  eula: true
  serverName: "Cedrics Server"
  difficulty: normal
  maxPlayers: 20
  gameMode: survival
  levelSeed: ""
  onlineMode: true
  serviceType: NodePort
  nodePort: 30000
  extraEnv:
    VERSION: "1.26.23.0"

nodeSelector:
  kubernetes.io/hostname: k3s-worker-01

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 2000m

persistence:
  storageClass: longhorn
  dataDir:
    enabled: true